name: pzn_belajar_dart_library
description: Library from Rio Achyar
version: 1.5.0
homepage: https://www.gremory.my.id
repository: https://github.com/RIOKOWI/pzn_belajar_dart_library

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
# dependencies:
#   path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
